import { Blog } from './blog'

export const BLOGS : Blog[] = [
    {
        id : '0',
        heading : 'An Overview of Next-Generation JavaScript Features for React Apps',
        subHeading : 'Next-generation JavaScript uses arrow functions, let, const, and other updated syntax',
        image : '../../assets/images/demo-detail.jpeg',
        category : 'Web Development',
        author : 'Shubham Kukreja',
        content : "Next-generation JavaScript could be thought of as the latest version of ECMAScript, the standardized specification for JavaScript.Each version endeavors to improve upon and add new functionality to this increasingly popular programming language. JavaScript has taken over the world of software development.According to Codeburst.io, JavaScript is the top programming language for developers. It was recognized as the most popular programming language in the Stack Overflow Developer Survey 2019 and it is the most popular programming language on GitHub.Needless to say JavaScript is a key language for software developers to know.Stack Overflow Developer Survey Results 2019:",
        likes : 52,
        date : '2011-12-02T17:57:28.556094Z',
    },
    {
        id : '1',
        heading : 'An Overview of Next-Generation JavaScript Features for React Apps',
        subHeading : 'Next-generation JavaScript uses arrow functions, let, const, and other updated syntax',
        image : '../../assets/images/demo-detail.jpeg',
        category : 'Web Development',
        author : 'Shubham Kukreja',
        content : "Next-generation JavaScript could be thought of as the latest version of ECMAScript, the standardized specification for JavaScript.Each version endeavors to improve upon and add new functionality to this increasingly popular programming language. JavaScript has taken over the world of software development.According to Codeburst.io, JavaScript is the top programming language for developers. It was recognized as the most popular programming language in the Stack Overflow Developer Survey 2019 and it is the most popular programming language on GitHub.Needless to say JavaScript is a key language for software developers to know.Stack Overflow Developer Survey Results 2019:",
        likes : 52,
        date : '2011-12-02T17:57:28.556094Z',
    },
    {
        id : '2',
        heading : 'An Overview of Next-Generation JavaScript Features for React Apps',
        subHeading : 'Next-generation JavaScript uses arrow functions, let, const, and other updated syntax',
        image : '../../assets/images/demo-detail.jpeg',
        category : 'Web Development',
        author : 'Shubham Kukreja',
        content : "Next-generation JavaScript could be thought of as the latest version of ECMAScript, the standardized specification for JavaScript.Each version endeavors to improve upon and add new functionality to this increasingly popular programming language. JavaScript has taken over the world of software development.According to Codeburst.io, JavaScript is the top programming language for developers. It was recognized as the most popular programming language in the Stack Overflow Developer Survey 2019 and it is the most popular programming language on GitHub.Needless to say JavaScript is a key language for software developers to know.Stack Overflow Developer Survey Results 2019:",
        likes : 52,
        date : '2011-12-02T17:57:28.556094Z',
    },
    {
        id : '3',
        heading : 'An Overview of Next-Generation JavaScript Features for React Apps',
        subHeading : 'Next-generation JavaScript uses arrow functions, let, const, and other updated syntax',
        image : '../../assets/images/demo-detail.jpeg',
        category : 'Web Development',
        author : 'Shubham Kukreja',
        content : "Next-generation JavaScript could be thought of as the latest version of ECMAScript, the standardized specification for JavaScript.Each version endeavors to improve upon and add new functionality to this increasingly popular programming language. JavaScript has taken over the world of software development.According to Codeburst.io, JavaScript is the top programming language for developers. It was recognized as the most popular programming language in the Stack Overflow Developer Survey 2019 and it is the most popular programming language on GitHub.Needless to say JavaScript is a key language for software developers to know.Stack Overflow Developer Survey Results 2019:",
        likes : 52,
        date : '2011-12-02T17:57:28.556094Z',
    },
    {
        id : '4',
        heading : 'An Overview of Next-Generation JavaScript Features for React Apps',
        subHeading : 'Next-generation JavaScript uses arrow functions, let, const, and other updated syntax',
        image : '../../assets/images/demo-detail.jpeg',
        category : 'Web Development',
        author : 'Shubham Kukreja',
        content : "Next-generation JavaScript could be thought of as the latest version of ECMAScript, the standardized specification for JavaScript.Each version endeavors to improve upon and add new functionality to this increasingly popular programming language. JavaScript has taken over the world of software development.According to Codeburst.io, JavaScript is the top programming language for developers. It was recognized as the most popular programming language in the Stack Overflow Developer Survey 2019 and it is the most popular programming language on GitHub.Needless to say JavaScript is a key language for software developers to know.Stack Overflow Developer Survey Results 2019:",
        likes : 52,
        date : '2011-12-02T17:57:28.556094Z',
    },
]